name: Python Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run tests
        run: python -m unittest CalcTest.py
      
      - name: Install coverage tool
        run: pip install coverage flake8

      - name: Run coverage test
        run: coverage run -m unittest CalcTest.py

      - name: Show coverage report
        run: coverage report -m

      - name: Static analysis
        run: flake8 . --max-line-length=100
